//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGUSService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location_V4", Namespace="http://www.serviceobjects.com")]
    public partial class Location_V4 : object
    {
        
        private AGUSService.Error ErrorField;
        
        private string LevelField;
        
        private string LevelDescriptionField;
        
        private string LatitudeField;
        
        private string LongitudeField;
        
        private string ZipField;
        
        private AGUSService.InformationComponent[] InformationComponentsField;
        
        private string DebugField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AGUSService.Error Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Level
        {
            get
            {
                return this.LevelField;
            }
            set
            {
                this.LevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LevelDescription
        {
            get
            {
                return this.LevelDescriptionField;
            }
            set
            {
                this.LevelDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Zip
        {
            get
            {
                return this.ZipField;
            }
            set
            {
                this.ZipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public AGUSService.InformationComponent[] InformationComponents
        {
            get
            {
                return this.InformationComponentsField;
            }
            set
            {
                this.InformationComponentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Debug
        {
            get
            {
                return this.DebugField;
            }
            set
            {
                this.DebugField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://www.serviceobjects.com")]
    public partial class Error : object
    {
        
        private string DescField;
        
        private string NumberField;
        
        private string LocationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Desc
        {
            get
            {
                return this.DescField;
            }
            set
            {
                this.DescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Location
        {
            get
            {
                return this.LocationField;
            }
            set
            {
                this.LocationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformationComponent", Namespace="http://www.serviceobjects.com")]
    public partial class InformationComponent : object
    {
        
        private string NameField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZipCodeInfo", Namespace="http://www.serviceobjects.com")]
    public partial class ZipCodeInfo : object
    {
        
        private AGUSService.Error ErrorField;
        
        private string CityField;
        
        private string StateField;
        
        private string CountyField;
        
        private string AreaCodeField;
        
        private string CityAbbreviationField;
        
        private string CityTypeField;
        
        private string CountyFIPSField;
        
        private string StateFIPSField;
        
        private string TimeZoneField;
        
        private string DayLightSavingsField;
        
        private string MSAField;
        
        private string MDField;
        
        private string CBSAField;
        
        private string PMSAField;
        
        private string DMAField;
        
        private string LatitudeField;
        
        private string LongitudeField;
        
        private string ZipField;
        
        private AGUSService.CityAlternativeName CityAlternativeNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AGUSService.Error Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string County
        {
            get
            {
                return this.CountyField;
            }
            set
            {
                this.CountyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AreaCode
        {
            get
            {
                return this.AreaCodeField;
            }
            set
            {
                this.AreaCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CityAbbreviation
        {
            get
            {
                return this.CityAbbreviationField;
            }
            set
            {
                this.CityAbbreviationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CityType
        {
            get
            {
                return this.CityTypeField;
            }
            set
            {
                this.CityTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CountyFIPS
        {
            get
            {
                return this.CountyFIPSField;
            }
            set
            {
                this.CountyFIPSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string StateFIPS
        {
            get
            {
                return this.StateFIPSField;
            }
            set
            {
                this.StateFIPSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string TimeZone
        {
            get
            {
                return this.TimeZoneField;
            }
            set
            {
                this.TimeZoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string DayLightSavings
        {
            get
            {
                return this.DayLightSavingsField;
            }
            set
            {
                this.DayLightSavingsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string MSA
        {
            get
            {
                return this.MSAField;
            }
            set
            {
                this.MSAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string MD
        {
            get
            {
                return this.MDField;
            }
            set
            {
                this.MDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string CBSA
        {
            get
            {
                return this.CBSAField;
            }
            set
            {
                this.CBSAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string PMSA
        {
            get
            {
                return this.PMSAField;
            }
            set
            {
                this.PMSAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string DMA
        {
            get
            {
                return this.DMAField;
            }
            set
            {
                this.DMAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string Zip
        {
            get
            {
                return this.ZipField;
            }
            set
            {
                this.ZipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public AGUSService.CityAlternativeName CityAlternativeName
        {
            get
            {
                return this.CityAlternativeNameField;
            }
            set
            {
                this.CityAlternativeNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="CityAlternativeName", Namespace="http://www.serviceobjects.com", ItemName="string")]
    public class CityAlternativeName : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReverseAddress", Namespace="http://www.serviceobjects.com")]
    public partial class ReverseAddress : object
    {
        
        private AGUSService.Error ErrorField;
        
        private string AddressField;
        
        private string CityField;
        
        private string StateField;
        
        private string ZipField;
        
        private string CountyField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AGUSService.Error Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Zip
        {
            get
            {
                return this.ZipField;
            }
            set
            {
                this.ZipField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string County
        {
            get
            {
                return this.CountyField;
            }
            set
            {
                this.CountyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistanceToWaterInfo", Namespace="http://www.serviceobjects.com")]
    public partial class DistanceToWaterInfo : object
    {
        
        private AGUSService.Error ErrorField;
        
        private string DistanceToWaterField;
        
        private string LatitudeField;
        
        private string LongitudeField;
        
        private string WaterLatField;
        
        private string WaterLonField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AGUSService.Error Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DistanceToWater
        {
            get
            {
                return this.DistanceToWaterField;
            }
            set
            {
                this.DistanceToWaterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string WaterLat
        {
            get
            {
                return this.WaterLatField;
            }
            set
            {
                this.WaterLatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string WaterLon
        {
            get
            {
                return this.WaterLonField;
            }
            set
            {
                this.WaterLonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DistanceBetweenInfo", Namespace="http://www.serviceobjects.com")]
    public partial class DistanceBetweenInfo : object
    {
        
        private AGUSService.Error ErrorField;
        
        private string MilesBetweenField;
        
        private string KilometersBetweenField;
        
        private string FeetBetweenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public AGUSService.Error Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MilesBetween
        {
            get
            {
                return this.MilesBetweenField;
            }
            set
            {
                this.MilesBetweenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string KilometersBetween
        {
            get
            {
                return this.KilometersBetweenField;
            }
            set
            {
                this.KilometersBetweenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FeetBetween
        {
            get
            {
                return this.FeetBetweenField;
            }
            set
            {
                this.FeetBetweenField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.serviceobjects.com", ConfigurationName="AGUSService.IGCRSoapService")]
    public interface IGCRSoapService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IGCRSoapService/GetBestMatch_V4", ReplyAction="http://www.serviceobjects.com/IGCRSoapService/GetBestMatch_V4Response")]
        System.Threading.Tasks.Task<AGUSService.Location_V4> GetBestMatch_V4Async(string Address, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IGCRSoapService/GetZipInfo", ReplyAction="http://www.serviceobjects.com/IGCRSoapService/GetZipInfoResponse")]
        System.Threading.Tasks.Task<AGUSService.ZipCodeInfo> GetZipInfoAsync(string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IGCRSoapService/GetReverseLocation", ReplyAction="http://www.serviceobjects.com/IGCRSoapService/GetReverseLocationResponse")]
        System.Threading.Tasks.Task<AGUSService.ReverseAddress> GetReverseLocationAsync(string Latitude, string Longitude, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IGCRSoapService/GetDistanceToWater", ReplyAction="http://www.serviceobjects.com/IGCRSoapService/GetDistanceToWaterResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DistanceToWaterInfo")]
        System.Threading.Tasks.Task<AGUSService.DistanceToWaterInfo> GetDistanceToWaterAsync(string Latitude, string Longitude, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IGCRSoapService/GetDistanceToWaterByAddress", ReplyAction="http://www.serviceobjects.com/IGCRSoapService/GetDistanceToWaterByAddressResponse" +
            "")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DistanceToWaterInfo")]
        System.Threading.Tasks.Task<AGUSService.DistanceToWaterInfo> GetDistanceToWaterByAddressAsync(string Address, string City, string State, string PostalCode, string LicenseKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.serviceobjects.com/IGCRSoapService/GetDistance", ReplyAction="http://www.serviceobjects.com/IGCRSoapService/GetDistanceResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DistanceBetweenInfo")]
        System.Threading.Tasks.Task<AGUSService.DistanceBetweenInfo> GetDistanceAsync(string FromLatitude, string FromLongitude, string ToLatitude, string ToLongitude, string LicenseKey);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IGCRSoapServiceChannel : AGUSService.IGCRSoapService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class GCRSoapServiceClient : System.ServiceModel.ClientBase<AGUSService.IGCRSoapService>, AGUSService.IGCRSoapService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GCRSoapServiceClient() : 
                base(GCRSoapServiceClient.GetDefaultBinding(), GCRSoapServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DOTSGeoCoder.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GCRSoapServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(GCRSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), GCRSoapServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GCRSoapServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GCRSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GCRSoapServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GCRSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GCRSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AGUSService.Location_V4> GetBestMatch_V4Async(string Address, string City, string State, string PostalCode, string LicenseKey)
        {
            return base.Channel.GetBestMatch_V4Async(Address, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AGUSService.ZipCodeInfo> GetZipInfoAsync(string PostalCode, string LicenseKey)
        {
            return base.Channel.GetZipInfoAsync(PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AGUSService.ReverseAddress> GetReverseLocationAsync(string Latitude, string Longitude, string LicenseKey)
        {
            return base.Channel.GetReverseLocationAsync(Latitude, Longitude, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AGUSService.DistanceToWaterInfo> GetDistanceToWaterAsync(string Latitude, string Longitude, string LicenseKey)
        {
            return base.Channel.GetDistanceToWaterAsync(Latitude, Longitude, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AGUSService.DistanceToWaterInfo> GetDistanceToWaterByAddressAsync(string Address, string City, string State, string PostalCode, string LicenseKey)
        {
            return base.Channel.GetDistanceToWaterByAddressAsync(Address, City, State, PostalCode, LicenseKey);
        }
        
        public System.Threading.Tasks.Task<AGUSService.DistanceBetweenInfo> GetDistanceAsync(string FromLatitude, string FromLongitude, string ToLatitude, string ToLongitude, string LicenseKey)
        {
            return base.Channel.GetDistanceAsync(FromLatitude, FromLongitude, ToLatitude, ToLongitude, LicenseKey);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DOTSGeoCoder))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DOTSGeoCoder))
            {
                return new System.ServiceModel.EndpointAddress("https://sws.serviceobjects.com/GCR/soap.svc/SOAP");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GCRSoapServiceClient.GetBindingForEndpoint(EndpointConfiguration.DOTSGeoCoder);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GCRSoapServiceClient.GetEndpointAddress(EndpointConfiguration.DOTSGeoCoder);
        }
        
        public enum EndpointConfiguration
        {
            
            DOTSGeoCoder,
        }
    }
}
